# import time
# import config
# from generate import generate

# def judge(question: str, expects: str, answer: str, results: list) -> bool:
#     """
#     Evaluates a single Q&A pair using an LLM judge with built-in pacing.
#     """
#     context = "\n".join(r.text for r in results)
#     rule = "Criterion: Retrieved chunks contain the answer."

#     prompt = f"""
#     You are an impartial strict judge evaluating an AI system's response.

#     Question asked by user: {question}
#     Answer generated by system: {answer}
#     Context retrieved: {context}

#     {rule}

#     Does the generated answer strictly meet this criterion?
#     Answer ONLY with 'YES' or 'NO'. Do not include any other text.
#     """


#     time.sleep(4)

#     response_text = generate(prompt, cache=False)
#     result = response_text.strip().upper()

#     return "YES" in result